### ISSUE TITLE
New haproxy Javascript SDK/API

### ISSUE THREAD

**Issue by shauntarves** [Treyone/ha-api#4]
Since this project seems abandoned, please see [haproxy-sdk](https://github.com/jackpinetech/haproxy-sdk) and [haproxy-api](https://github.com/jackpinetech/haproxy-api)

**Comment by Treyone** [comment]
Indeed it is, I can transfer you ownership if you want, or just keep a README that points to your projects !

**Comment by shauntarves** [comment]
Any link would be helpful. No need to transfer ownership!

Thanks for spreading the word.

**Comment by Treyone** [comment]
There you go https://github.com/Treyone/ha-api/commit/f33251665b9f478ae31a66f384bbbe869ea5a40c :)
